/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppDecisionsRouteImport } from './routes/_app/decisions'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppLearnRouteImport } from './routes/_app/learn'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSimulatorRouteImport } from './routes/_app/simulator'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppLearnSlugRouteImport } from './routes/_app/learn.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnSlugRoute = AppLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppLearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/assets': typeof AppAssetsRoute
  '/budgets': typeof AppBudgetsRoute
  '/decisions': typeof AppDecisionsRoute
  '/insights': typeof AppInsightsRoute
  '/learn': typeof AppLearnRouteWithChildren
  '/report': typeof AppReportRoute
  '/settings': typeof AppSettingsRoute
  '/simulator': typeof AppSimulatorRoute
  '/transactions': typeof AppTransactionsRoute
  '/learn/$slug': typeof AppLearnSlugRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assets': typeof AppAssetsRoute
  '/budgets': typeof AppBudgetsRoute
  '/decisions': typeof AppDecisionsRoute
  '/insights': typeof AppInsightsRoute
  '/learn': typeof AppLearnRouteWithChildren
  '/report': typeof AppReportRoute
  '/settings': typeof AppSettingsRoute
  '/simulator': typeof AppSimulatorRoute
  '/transactions': typeof AppTransactionsRoute
  '/': typeof AppIndexRoute
  '/learn/$slug': typeof AppLearnSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/decisions': typeof AppDecisionsRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/learn': typeof AppLearnRouteWithChildren
  '/_app/report': typeof AppReportRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/simulator': typeof AppSimulatorRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/learn/$slug': typeof AppLearnSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assets'
    | '/budgets'
    | '/decisions'
    | '/insights'
    | '/learn'
    | '/report'
    | '/settings'
    | '/simulator'
    | '/transactions'
    | '/learn/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assets'
    | '/budgets'
    | '/decisions'
    | '/insights'
    | '/learn'
    | '/report'
    | '/settings'
    | '/simulator'
    | '/transactions'
    | '/'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/assets'
    | '/_app/budgets'
    | '/_app/decisions'
    | '/_app/insights'
    | '/_app/learn'
    | '/_app/report'
    | '/_app/settings'
    | '/_app/simulator'
    | '/_app/transactions'
    | '/_app/'
    | '/_app/learn/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulator': {
      id: '/_app/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/$slug': {
      id: '/_app/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AppLearnSlugRouteImport
      parentRoute: typeof AppLearnRoute
    }
  }
}

interface AppLearnRouteChildren {
  AppLearnSlugRoute: typeof AppLearnSlugRoute
}

const AppLearnRouteChildren: AppLearnRouteChildren = {
  AppLearnSlugRoute: AppLearnSlugRoute,
}

const AppLearnRouteWithChildren = AppLearnRoute._addFileChildren(
  AppLearnRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLearnRoute: typeof AppLearnRouteWithChildren
  AppReportRoute: typeof AppReportRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLearnRoute: AppLearnRouteWithChildren,
  AppReportRoute: AppReportRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
